In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/Travel.csv')
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

### **Data Cleaning**

In [ ]:
cat_values = ['TypeofContact','Occupation','ProductPitched','MaritalStatus', 'Designation', 'Gender']

for value in cat_values:
  print(df[value].value_counts())

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64
Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64
ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64
MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64
Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64
Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [ ]:
df['MaritalStatus'] = df['MaritalStatus'].replace('Unmarried', 'Single' )
df['Gender'] = df['Gender'].replace('Fe Male', 'Female' )

In [ ]:
df['MaritalStatus'].unique()

array(['Single', 'Divorced', 'Married'], dtype=object)

In [ ]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [ ]:
df.Age.fillna(df.Age.median(), inplace = True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace = True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace = True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.median(), inplace = True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.median(), inplace = True)
df.NumberOfTrips.fillna(df.NumberOfTrips.median(), inplace = True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.median(), inplace = True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(), inplace = True)

In [ ]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [ ]:
df.drop('CustomerID', inplace = True, axis = 1)

In [ ]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

### ***Feature Engineering***

In [ ]:
df['total visiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']

df.drop(columns= ['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'], axis = 1, inplace = True)
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,total visiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [ ]:
X = df.drop('ProdTaken', axis = 1)

In [ ]:
y = df['ProdTaken']

In [ ]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.20)
X_train.shape, X_test.shape

((3910, 17), (978, 17))

### ***Feature Transformation***

In [ ]:
cat_features = X.select_dtypes(include = 'object').columns
num_features = X.select_dtypes(exclude= 'object').columns

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer


scaler = StandardScaler()
encoder = OneHotEncoder(drop = 'first')

transformer = ColumnTransformer([('OneHotEncoder', encoder, cat_features ), ('StandardScaler',scaler,num_features )])

In [ ]:
print(transformer)

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'total visiting'],
      dtype='object'))])

In [ ]:
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)

### ***Model Building***

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, classification_report

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [ ]:
models = [ RandomForestClassifier(), GaussianNB(), KNeighborsClassifier(), SVC(),DecisionTreeClassifier() ]

for model in models:
  model.fit(X_train,y_train)
  y_pred = model.predict(X_test)

  print(model, '\nConfusion matrix \n', confusion_matrix(y_pred,y_test))
  print('Score' , accuracy_score(y_pred,y_test))
  print('Report', classification_report(y_pred,y_test))
  print('--------------------------------------------------')

RandomForestClassifier()
Confusion matrix
 [[775  70]
 [  8 125]]
Score 0.9202453987730062
Report               precision    recall  f1-score   support

           0       0.99      0.92      0.95       845
           1       0.64      0.94      0.76       133

    accuracy                           0.92       978
   macro avg       0.82      0.93      0.86       978
weighted avg       0.94      0.92      0.93       978

--------------------------------------------------
GaussianNB()
Confusion matrix
 [[536  60]
 [247 135]]
Score 0.6860940695296524
Report               precision    recall  f1-score   support

           0       0.68      0.90      0.78       596
           1       0.69      0.35      0.47       382

    accuracy                           0.69       978
   macro avg       0.69      0.63      0.62       978
weighted avg       0.69      0.69      0.66       978

--------------------------------------------------
KNeighborsClassifier()
Confusion matrix
 [[757  80]
 [ 26 115]]
Score 0.8916155419222904
Report               precision    recall  f1-score   support

           0       0.97      0.90      0.93       837
           1       0.59      0.82      0.68       141

    accuracy                           0.89       978
   macro avg       0.78      0.86      0.81       978
weighted avg       0.91      0.89      0.90       978

--------------------------------------------------
SVC()
Confusion matrix
 [[767 120]
 [ 16  75]]
Score 0.8609406952965235
Report               precision    recall  f1-score   support

           0       0.98      0.86      0.92       887
           1       0.38      0.82      0.52        91

    accuracy                           0.86       978
   macro avg       0.68      0.84      0.72       978
weighted avg       0.92      0.86      0.88       978

--------------------------------------------------
DecisionTreeClassifier()
Confusion matrix
 [[764  44]
 [ 19 151]]
Score 0.9355828220858896
Report               precision    recall  f1-score   support

           0       0.98      0.95      0.96       808
           1       0.77      0.89      0.83       170

    accuracy                           0.94       978
   macro avg       0.88      0.92      0.89       978
weighted avg       0.94      0.94      0.94       978

--------------------------------------------------

### ***Hyperparameter Tuning***

In [ ]:
params = { 'n_estimators' : [100,120,140,150] ,
          'criterion': ['gini', 'entropy', 'log_los'],
           'max_depth' : [5,8,10,2],
           'min_samples_split' : [2,8,15,23],
           'max_features': [5,7,10, 'auto']
}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

randomcv = RandomizedSearchCV(estimator = RandomForestClassifier(), param_distributions = params, scoring= 'accuracy', cv = 3, verbose = 3, n_iter= 25)

In [ ]:
randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV 1/3] END criterion=gini, max_depth=8, max_features=10, min_samples_split=2, n_estimators=140;, score=0.873 total time=   0.9s
[CV 2/3] END criterion=gini, max_depth=8, max_features=10, min_samples_split=2, n_estimators=140;, score=0.886 total time=   1.1s
[CV 3/3] END criterion=gini, max_depth=8, max_features=10, min_samples_split=2, n_estimators=140;, score=0.881 total time=   1.1s
[CV 1/3] END criterion=log_los, max_depth=8, max_features=7, min_samples_split=2, n_estimators=140;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=8, max_features=7, min_samples_split=2, n_estimators=140;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=8, max_features=7, min_samples_split=2, n_estimators=140;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=10, max_features=10, min_samples_split=23, n_estimators=150;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=10, max_features=10, min_samples_split=23, n_estimators=150;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=10, max_features=10, min_samples_split=23, n_estimators=150;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=10, max_features=7, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=10, max_features=7, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=10, max_features=7, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 1/3] END criterion=gini, max_depth=10, max_features=10, min_samples_split=23, n_estimators=140;, score=0.871 total time=   1.0s
[CV 2/3] END criterion=gini, max_depth=10, max_features=10, min_samples_split=23, n_estimators=140;, score=0.874 total time=   0.7s
[CV 3/3] END criterion=gini, max_depth=10, max_features=10, min_samples_split=23, n_estimators=140;, score=0.870 total time=   0.7s
[CV 1/3] END criterion=log_los, max_depth=2, max_features=5, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=2, max_features=5, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=2, max_features=5, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END criterion=gini, max_depth=2, max_features=7, min_samples_split=8, n_estimators=150;, score=0.813 total time=   0.4s
[CV 2/3] END criterion=gini, max_depth=2, max_features=7, min_samples_split=8, n_estimators=150;, score=0.815 total time=   0.4s
[CV 3/3] END criterion=gini, max_depth=2, max_features=7, min_samples_split=8, n_estimators=150;, score=0.814 total time=   0.3s
[CV 1/3] END criterion=entropy, max_depth=8, max_features=7, min_samples_split=23, n_estimators=150;, score=0.857 total time=   0.6s
[CV 2/3] END criterion=entropy, max_depth=8, max_features=7, min_samples_split=23, n_estimators=150;, score=0.865 total time=   0.6s
[CV 3/3] END criterion=entropy, max_depth=8, max_features=7, min_samples_split=23, n_estimators=150;, score=0.862 total time=   0.6s
[CV 1/3] END criterion=gini, max_depth=10, max_features=10, min_samples_split=2, n_estimators=100;, score=0.888 total time=   0.7s
[CV 2/3] END criterion=gini, max_depth=10, max_features=10, min_samples_split=2, n_estimators=100;, score=0.906 total time=   0.8s
[CV 3/3] END criterion=gini, max_depth=10, max_features=10, min_samples_split=2, n_estimators=100;, score=0.893 total time=   0.8s
[CV 1/3] END criterion=gini, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=120;, score=nan total time=   0.0s
[CV 2/3] END criterion=gini, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=120;, score=nan total time=   0.0s
[CV 3/3] END criterion=gini, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=120;, score=nan total time=   0.0s
[CV 1/3] END criterion=entropy, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END criterion=entropy, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END criterion=entropy, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END criterion=entropy, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=140;, score=nan total time=   0.0s
[CV 2/3] END criterion=entropy, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=140;, score=nan total time=   0.0s
[CV 3/3] END criterion=entropy, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=140;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=8, max_features=7, min_samples_split=2, n_estimators=120;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=8, max_features=7, min_samples_split=2, n_estimators=120;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=8, max_features=7, min_samples_split=2, n_estimators=120;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=2, max_features=10, min_samples_split=23, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=2, max_features=10, min_samples_split=23, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=2, max_features=10, min_samples_split=23, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END criterion=gini, max_depth=8, max_features=10, min_samples_split=15, n_estimators=120;, score=0.869 total time=   0.9s
[CV 2/3] END criterion=gini, max_depth=8, max_features=10, min_samples_split=15, n_estimators=120;, score=0.880 total time=   0.9s
[CV 3/3] END criterion=gini, max_depth=8, max_features=10, min_samples_split=15, n_estimators=120;, score=0.873 total time=   0.7s
[CV 1/3] END criterion=log_los, max_depth=10, max_features=5, min_samples_split=8, n_estimators=120;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=10, max_features=5, min_samples_split=8, n_estimators=120;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=10, max_features=5, min_samples_split=8, n_estimators=120;, score=nan total time=   0.0s
[CV 1/3] END criterion=gini, max_depth=10, max_features=auto, min_samples_split=2, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END criterion=gini, max_depth=10, max_features=auto, min_samples_split=2, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END criterion=gini, max_depth=10, max_features=auto, min_samples_split=2, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=2, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END criterion=entropy, max_depth=10, max_features=auto, min_samples_split=23, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END criterion=entropy, max_depth=10, max_features=auto, min_samples_split=23, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END criterion=entropy, max_depth=10, max_features=auto, min_samples_split=23, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=5, max_features=5, min_samples_split=2, n_estimators=150;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=5, max_features=5, min_samples_split=2, n_estimators=150;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=5, max_features=5, min_samples_split=2, n_estimators=150;, score=nan total time=   0.0s
[CV 1/3] END criterion=log_los, max_depth=10, max_features=auto, min_samples_split=15, n_estimators=140;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=10, max_features=auto, min_samples_split=15, n_estimators=140;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=10, max_features=auto, min_samples_split=15, n_estimators=140;, score=nan total time=   0.0s
[CV 1/3] END criterion=entropy, max_depth=5, max_features=7, min_samples_split=8, n_estimators=120;, score=0.837 total time=   0.4s
[CV 2/3] END criterion=entropy, max_depth=5, max_features=7, min_samples_split=8, n_estimators=120;, score=0.840 total time=   0.4s
[CV 3/3] END criterion=entropy, max_depth=5, max_features=7, min_samples_split=8, n_estimators=120;, score=0.850 total time=   0.4s
[CV 1/3] END criterion=log_los, max_depth=8, max_features=auto, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 2/3] END criterion=log_los, max_depth=8, max_features=auto, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 3/3] END criterion=log_los, max_depth=8, max_features=auto, min_samples_split=15, n_estimators=150;, score=nan total time=   0.0s
[CV 1/3] END criterion=entropy, max_depth=5, max_features=7, min_samples_split=23, n_estimators=150;, score=0.839 total time=   0.5s
[CV 2/3] END criterion=entropy, max_depth=5, max_features=7, min_samples_split=23, n_estimators=150;, score=0.837 total time=   0.5s
[CV 3/3] END criterion=entropy, max_depth=5, max_features=7, min_samples_split=23, n_estimators=150;, score=0.850 total time=   0.5s

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=25,
                   param_distributions={'criterion': ['gini', 'entropy',
                                                      'log_los'],
                                        'max_depth': [5, 8, 10, 2],
                                        'max_features': [5, 7, 10, 'auto'],
                                        'min_samples_split': [2, 8, 15, 23],
                                        'n_estimators': [100, 120, 140, 150]},
                   scoring='accuracy', verbose=3)

In [ ]:
y_pred = randomcv.predict(X_test)

In [ ]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[773  87]
 [ 10 108]]
0.9008179959100204
              precision    recall  f1-score   support

           0       0.99      0.90      0.94       860
           1       0.55      0.92      0.69       118

    accuracy                           0.90       978
   macro avg       0.77      0.91      0.82       978
weighted avg       0.93      0.90      0.91       978

In [ ]:
randomcv.best_params_

{'n_estimators': 100,
 'min_samples_split': 2,
 'max_features': 10,
 'max_depth': 10,
 'criterion': 'gini'}